-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "itemDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "summaryDiscount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "summaryDiscountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "discountPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
